version = "1.0.0"
modLoader = "javafml"
loaderVersion = "[47, )"
license = "MIT"
[[mods]]
modId = "recipemod"
version = "1.0.0"
displayName = "RecipeMod"
description = "Override Custom Workbench recipes from other mods via config"
logoFile = "logo.png"
authors = ["Zeorez"]
license = "MIT"

[[dependencies.recipemod]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.4.0, )" 
    ordering = "NONE"

[[dependencies.recipemod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1, )"
    ordering = "NONE"

[[dependencies.recipemod]]
    modId = "trajanstanks"
    mandatory = false
    versionRange = "[2.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.recipemod]]
    modId = "trajanscore"
    mandatory = false
    versionRange = "[1.0,)"
    ordering = "AFTER"
    side = "BOTH"
